### ISSUE TITLE
轮盘值在拨动时，取值不准确问题

### ISSUE THREAD

**Issue by huangjian199304** [k186/pd-select#10]
大佬，刚才用了你的2.0版本，发现在触摸拨动时，拨动时有时会拨不动，取值有问题，有时候会突然跳回之前拨动的值位置。

**Comment by huangjian199304** [comment]
@k186 麻烦大佬再看下哈。

**Comment by k186** [comment]
demo 里面我写了个3秒的延迟 来测试 手动更新 所以会有你说的这个现象

Meng Star <notifications@github.com> 于2018年8月1日周三 下午5:07写道：

**Comment by huangjian199304** [comment]
value(val, oldValue) {
                if (val != oldValue) {
                    Object.assign(this.$data, this.$options.data());
                    this.init(false);
                }
            }
这个代码，不使用的时候，滑块滑动的速度是正常的。反之拨动一下滑块，滑块就会持续旋转一段时间，导致有时候无法选取正确的滑块值，而且有时候滑块值点击时会迅速改变成其它值

**Comment by k186** [comment]
@huangjian199304 你代码拉错了吧。。。最新代码没这句话。。。看分支。。这个是以前的一个hack 代码 已经去掉了的

**Comment by huangjian199304** [comment]
这段代码可以重置这个滑块值吧，我现在需要的就是这个功能，所以问下大佬这段代码是不是可以修改下，正常的重置滑块值为初始值 @k186

**Comment by k186** [comment]
@huangjian199304 不能放在watch 里面。。

**Comment by huangjian199304** [comment]
那应该另写方法，实现这段代码吗，然后别处重置时调用这个方法吗？大佬。 @k186

**Comment by k186** [comment]
嗯,参照demo 的那个 延迟 你自己在封一层吧

Meng Star <notifications@github.com> 于2018年8月1日周三 下午6:28写道：
