### ISSUE TITLE
用作获取时间的组件，对v-model值重新赋值，然后调用init()方法之后，显示选中的值不对

### ISSUE THREAD

**Issue by hwyeeee** [k186/pd-select#12]
我在点击按钮之后重新对绑定的值赋值，接着执行init()方法，希望能够将对应的值显示为选中效果
\<pd-select-item ref="year" :listData="YearArr" v-model="year" type="cycle"></pd-select-item>
this.year = this.getDateYear(date) + '年'; 
this.$refs.year.init()
结果每次执行之后都会发现位置出错，@k186 希望能够解答一下

**Comment by k186** [comment]
@hwyeeee 麻烦提供下完整的代码片段 包括 YearArr的数据 getDateYear的返回值样例。

**Comment by hwyeeee** [comment]
`<template>
  <div id="app">
    <button @click="getTime">获取时间</button>
    <br>
    <input type="text" v-model="date">
    <br>
    <button @click="after">重置时间</button>
    <pd-select-box style="position: fixed;bottom: 0;width: 100%">
      <pd-select-item ref="year" :listData="yearArr" v-model="year" type="cycle"></pd-select-item>
      <pd-select-item ref="month" :listData="monthArr" v-model="month" type="cycle"></pd-select-item>
      <pd-select-item ref="day" :listData="dayArr" v-model="day" type="cycle"></pd-select-item>
      <pd-select-item ref="hour" :listData="hourArr" v-model="hour" type="cycle"></pd-select-item>
    </pd-select-box>
  </div>
</template>

<script>
export default {
  name: 'app',
  data () {
    return {
      yearArr: Array.from({length: 31}, (value, index) => index + 2000),
      monthArr: Array.from({length: 12}, (value, index) => index + 1),
      dayArr: Array.from({length: 31}, (value, index) => index + 1),
      hourArr: Array.from({length: 24}, (value, index) => index),
      year: '',
      month: '',
      day: '',
      hour: '',
      date: ''
    }
  },
  mounted(){
    setTimeout(()=>{
      this.after()
    },300)
  },
  methods: {
    getTime () {
      this.date = this.year + '-' + this.month + '-' + this.day + ' ' + this.hour
    },
    after () {
      let curDate = new Date()
      this.year = curDate.getFullYear()
      this.month = (curDate.getMonth() + 1)
      this.day = curDate.getDate()
      this.hour = curDate.getHours()
      this.$refs.year.init()
      this.$refs.month.init()
      this.$refs.day.init()
      this.$refs.hour.init()
    }
  }
}
</script>`

**Comment by hwyeeee** [comment]
`<template>
  <div id="app">
    <button @click="getTime">获取时间</button>
    <br>
    <input type="text" v-model="date">
    <br>
    <button @click="after">重置时间</button>
    <pd-select-box style="position: fixed;bottom: 0;width: 100%">
      <pd-select-item ref="year" :listData="yearArr" v-model="year" type="cycle"></pd-select-item>
      <pd-select-item ref="month" :listData="monthArr" v-model="month" type="cycle"></pd-select-item>
      <pd-select-item ref="day" :listData="dayArr" v-model="day" type="cycle"></pd-select-item>
      <pd-select-item ref="hour" :listData="hourArr" v-model="hour" type="cycle"></pd-select-item>
    </pd-select-box>
  </div>
</template>`
`<script>
export default {
  name: 'app',
  data () {
    return {
      yearArr: Array.from({length: 31}, (value, index) => index + 2000),
      monthArr: Array.from({length: 12}, (value, index) => index + 1),
      dayArr: Array.from({length: 31}, (value, index) => index + 1),
      hourArr: Array.from({length: 24}, (value, index) => index),
      year: '',
      month: '',
      day: '',
      hour: '',
      date: ''
    }
  },
  mounted(){
    setTimeout(()=>{
      this.after()
    },300)
  },
  methods: {
    getTime () {
      this.date = this.year + '-' + this.month + '-' + this.day + ' ' + this.hour
    },
    after () {
      let curDate = new Date()
      this.year = curDate.getFullYear()
      this.month = (curDate.getMonth() + 1)
      this.day = curDate.getDate()
      this.hour = curDate.getHours()
      this.$refs.year.init()
      this.$refs.month.init()
      this.$refs.day.init()
      this.$refs.hour.init()
    }
  }
}
</script>`

**Comment by hwyeeee** [comment]
\<template>
  \<div id="app">
    \<button @click="getTime">获取时间</button>
    \<br>
    \<input type="text" v-model="date">
    \<br>
    \<button @click="after">重置时间</button>
    \<pd-select-box style="position: fixed;bottom: 0;width: 100%">
      \<pd-select-item ref="year" :listData="yearArr" v-model="year" type="cycle"></pd-select-item>
      \<pd-select-item ref="month" :listData="monthArr" v-model="month" type="cycle"></pd-select-item>
      \<pd-select-item ref="day" :listData="dayArr" v-model="day" type="cycle"></pd-select-item>
      \<pd-select-item ref="hour" :listData="hourArr" v-model="hour" type="cycle"></pd-select-item>
    \</pd-select-box>
  \</div>
\</template>
`<script>
export default {
  name: 'app',
  data () {
    return {
      yearArr: Array.from({length: 31}, (value, index) => index + 2000),
      monthArr: Array.from({length: 12}, (value, index) => index + 1),
      dayArr: Array.from({length: 31}, (value, index) => index + 1),
      hourArr: Array.from({length: 24}, (value, index) => index),
      year: '',
      month: '',
      day: '',
      hour: '',
      date: ''
    }
  },
  mounted(){
    setTimeout(()=>{
      this.after()
    },300)
  },
  methods: {
    getTime () {
      this.date = this.year + '-' + this.month + '-' + this.day + ' ' + this.hour
    },
    after () {
      let curDate = new Date()
      this.year = curDate.getFullYear()
      this.month = (curDate.getMonth() + 1)
      this.day = curDate.getDate()
      this.hour = curDate.getHours()
      this.$refs.year.init()
      this.$refs.month.init()
      this.$refs.day.init()
      this.$refs.hour.init()
    }
  }
}
</script>`

**Comment by hwyeeee** [comment]
\<template>
  \<div id="app">
    \<button @click="getTime">获取时间</button>
    \<br>
    \<input type="text" v-model="date">
    \<br>
    \<button @click="after">重置时间</button>
    \<pd-select-box style="position: fixed;bottom: 0;width: 100%">
      \<pd-select-item ref="year" :listData="yearArr" v-model="year" type="cycle"></pd-select-item>
      \<pd-select-item ref="month" :listData="monthArr" v-model="month" type="cycle"></pd-select-item>
      \<pd-select-item ref="day" :listData="dayArr" v-model="day" type="cycle"></pd-select-item>
      \<pd-select-item ref="hour" :listData="hourArr" v-model="hour" type="cycle"></pd-select-item>
    \</pd-select-box>
  \</div>
\</template>
<script>
export default {
  name: 'app',
  data () {
    return {
      yearArr: Array.from({length: 31}, (value, index) => index + 2000),
      monthArr: Array.from({length: 12}, (value, index) => index + 1),
      dayArr: Array.from({length: 31}, (value, index) => index + 1),
      hourArr: Array.from({length: 24}, (value, index) => index),
      year: '',
      month: '',
      day: '',
      hour: '',
      date: ''
    }
  },
  mounted(){
    setTimeout(()=>{
      this.after()
    },300)
  },
  methods: {
    getTime () {
      this.date = this.year + '-' + this.month + '-' + this.day + ' ' + this.hour
    },
    after () {
      let curDate = new Date()
      this.year = curDate.getFullYear()
      this.month = (curDate.getMonth() + 1)
      this.day = curDate.getDate()
      this.hour = curDate.getHours()
      this.$refs.year.init()
      this.$refs.month.init()
      this.$refs.day.init()
      this.$refs.hour.init()
    }
  }
}
</script>

**Comment by hwyeeee** [comment]
\<template>
  \<div id="app">
    \<button @click="getTime">获取时间</button>
    \<br>
    \<input type="text" v-model="date">
    \<br>
    \<button @click="after">重置时间</button>
    \<pd-select-box style="position: fixed;bottom: 0;width: 100%">
      \<pd-select-item ref="year" :listData="yearArr" v-model="year" type="cycle"></pd-select-item>
      \<pd-select-item ref="month" :listData="monthArr" v-model="month" type="cycle"></pd-select-item>
      \<pd-select-item ref="day" :listData="dayArr" v-model="day" type="cycle"></pd-select-item>
      \<pd-select-item ref="hour" :listData="hourArr" v-model="hour" type="cycle"></pd-select-item>
    \</pd-select-box>
  \</div>
\</template>

`<script>
export default {
  name: 'app',
  data () {
    return {
      yearArr: Array.from({length: 31}, (value, index) => index + 2000),
      monthArr: Array.from({length: 12}, (value, index) => index + 1),
      dayArr: Array.from({length: 31}, (value, index) => index + 1),
      hourArr: Array.from({length: 24}, (value, index) => index),
      year: '',
      month: '',
      day: '',
      hour: '',
      date: ''
    }
  },
  mounted(){
    setTimeout(()=>{
      this.after()
    },300)
  },
  methods: {
    getTime () {
      this.date = this.year + '-' + this.month + '-' + this.day + ' ' + this.hour
    },
    after () {
      let curDate = new Date()
      this.year = curDate.getFullYear()
      this.month = (curDate.getMonth() + 1)
      this.day = curDate.getDate()
      this.hour = curDate.getHours()
      this.$refs.year.init()
      this.$refs.month.init()
      this.$refs.day.init()
      this.$refs.hour.init()
    }
  }
}
</script>`

@k186 ，测试时候的代码

**Comment by k186** [comment]
已经修复 安装最新版本就可以了

**Comment by hwyeeee** [comment]
thanks
