### ISSUE TITLE
请问有事件可以监听动画停止吗  我加个按钮点快的时候就拿不到值了

### ISSUE THREAD

**Issue by tanliang007** [k186/pd-select#2]

**Comment by k186** [comment]
@tanliang007 你按钮的取值逻辑能说一下吗？
这个方法里 getPickValue

**Comment by tanliang007** [comment]
就是手机上用的时候 ，我自己写的确定事件在里面把pick的值赋值给data，如果点快了，有的时候就不会发生改变 需要停一下让动画做完就可以，谢谢！

**Comment by k186** [comment]
@tanliang007 你把 $.emit 里面的延迟 给去掉就可以了
