### ISSUE TITLE
首次加载滚动框留白

### ISSUE THREAD

**Issue by ghost** [k186/pd-select#3]
请问下滚动的初始值我想设置为数据的中间部分，这样就不
![111](https://user-images.githubusercontent.com/28571205/34637892-dc75ebc2-f2fa-11e7-93d5-91a8ccef5c54.png)
会出现首次加载滚动框留白了，需要怎么设置。

**Comment by k186** [comment]
你这应该是css没引入导致的
  @fuhui2017
