### ISSUE TITLE
当前初始值不存在，请检查后listData范围！！

### ISSUE THREAD

**Issue by ghost** [k186/pd-select#4]
当前初始值不存在，请检查后listData范围！！
这个报错能改进吗

**Comment by k186** [comment]
@fuhui2017 这个是警告,提示你给的初始值不在你给的渲染范围内

**Comment by ghost** [comment]
请问下初始值如何设置 我看到你的demo里面也有这个警告 http://www.k186studio.com/demos/iosPicker/

**Comment by k186** [comment]
@fuhui2017 首页markdown 有说明
