### ISSUE TITLE
使用组件出错

### ISSUE THREAD

**Issue by zhanbohui** [k186/pd-select#6]
调用组件时，浏览器报Maximum call stack size exceeded。

**Comment by k186** [comment]
@zhanbohui 能贴出部分代码吗？

**Comment by zhanbohui** [comment]
@k186 
引用：
![image](https://user-images.githubusercontent.com/17806945/34711076-e0f8f56c-f558-11e7-9209-b3a2ae0bb196.png)
调用：
![image](https://user-images.githubusercontent.com/17806945/34711018-9931c416-f558-11e7-9400-33b48093dd90.png)

**Comment by k186** [comment]
@zhanbohui 你试着把其他插件先去掉，然后只留这个插件使用，看看具体是哪个插件造成的,应该是跟某个插件冲突了,我这边试了 都没问题
