### ISSUE TITLE
v-model 值改变时，dom选中项未改变

### ISSUE THREAD

**Issue by husilang** [k186/pd-select#7]
pd-select-item 组件 v-model的值改变时，页面上的选中项仍旧没变

**Comment by husilang** [comment]
我想要页面上的选中项跟着改变，该怎么办

**Comment by k186** [comment]
@husilang 你说的是不是外层动态修改组件v-model值,组件没有对应更新?我今天晚上看一下，最近在做2.0更新

**Comment by husilang** [comment]
嗯嗯，是的，谢谢

**Comment by k186** [comment]
2.0新增特性，目前只能绕过去，具体hack 代码看 https://github.com/k186/pd-select/blob/ver2.0/src/components/pdSelect/selectitem.vue 212行至216行 ，这会造成快速滚动有闪动现象；
ps:最近没时间更新，有兴趣的可以自己尝试fork 修改后推送

**Comment by huangjian199304** [comment]
倒着转取值有问题呀，从1转到12 的时候，变成2了，不是12

**Comment by k186** [comment]
@huangjian199304 取的是索引 不是值

**Comment by huangjian199304** [comment]
ok，但是到这转从1转12的时候，取的索引也不对呀，索引应该是11，而不是1吧，我把你的这个代码改了一下，倒着转就取的正确的索引了。
  /* 获取选中值 */
            getPickValue(move) {
                this.indexSend = (-move / 34);
            }

**Comment by k186** [comment]
@huangjian199304 你给下你完整的初始化配置

**Comment by huangjian199304** [comment]
其他的配置用的还是你写的那些，只在里面加了个鼠标事件以及修改了这段代码，其他的没有做修改@k186

**Comment by k186** [comment]
@huangjian199304 你这修改不对，以前我是校验过的，这几天空了，我看下。

**Comment by huangjian199304** [comment]
嗯，好的，之前你写的是取绝对值。有时间你看下@k186

**Comment by huangjian199304** [comment]
最好能把后续功能实现一下最好了😄。最好能有一些其他功能，比如达到某个条件，滑轮无法继续向一个方向继续拨动。移动端适配等。 @k186

**Comment by k186** [comment]
webpack 构建
modle 值不同步问题
圆环取值计算错误问题
fixed at ver2.0.0
移动端适配这个问题 现在暂时不做处理，因为移动端适配方案太多，有rem ，vh等，现在这个实际就是给移动端用的，pc端不建议使用这个插件

**Comment by huangjian199304** [comment]
大佬，请问如果我转动了这个轮盘值，我想做个重置按钮，点击把轮盘值恢复初始值该如何来做呢？我试了几次发现都不行，请问有什么解决方法吗？ @k186

**Comment by k186** [comment]
@huangjian199304 看demo,需要你手动调用组件的init 方法

**Comment by huangjian199304** [comment]
OK了，还有个问题，比如说我加个限定条件，当前滑块值为7的时候，然后不允许它继续向下滑，但是可以继续往上滑，这个该如何实现呢？ @k186

**Comment by k186** [comment]
@huangjian199304  换个思路你只给你需要的值 不准选的值不展示就可以了，你说的那种可以做，最近没时间搞，

**Comment by huangjian199304** [comment]
但是这个限定值也并不是固定的，可能在这个条件下阈值时7，但是可能在下个条件下阈值就可能是8，这样子限定值不展示会不会有问题呢？ @k186

**Comment by k186** [comment]
@huangjian199304 你每次限制 就相当于重新初始化 这个滚轮，所以不存在展示问题

**Comment by huangjian199304** [comment]
谢谢大佬，能不能给个好友位？以后可以继续请教你啊。 @k186

**Comment by k186** [comment]
微信:k1868548k
