### ISSUE TITLE
事件绑定错误

### ISSUE THREAD

**Issue by Gerogina6** [k186/pd-select#9]
`
 mounted() {
        // 事件綁定
        this.$el.addEventLister('touchstart',this.itemTouchStart)
        this.$el.addEventLister('touchmove',this.itemTouchMove)
        this.$el.addEventLister('touchend',this.itemTouchEnd)
`
这样写好像是不对的，获取不到dom，导致addEventLister `undefined`
log了一下$el、el、this.$el都undefined

**Comment by k186** [comment]
你的环境可能有问题，请确保建立了正确的vue 环境 这个是一个vue的 component  ，需要自己单独引入vue使用
